title: Robert Bahensky
description: Robert's personal webpage
url: https://jekyll-cv.stavrospanakakis.com
baseurl: ''
theme_skin: black

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
